### ISSUE TITLE
How to use mod?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [Celibistrial/freelook#1]
This mod is just what I've been looking for - a fabric version of the freelook mod that lunar has. How do I download something I can put in my `mods` folder?

**Comment by Celibistrial** [comment]
The build is in https://www.curseforge.com/minecraft/mc-mods/freelook-fabric

**Comment by Celibistrial** [comment]
put the jar in ur mods folder

**Comment by ChocolateLoverRaj** [comment]
@Celibistrial The mod worked. Thanks for [putting the download link the in the README](https://github.com/Celibistrial/freelook/commit/be86046b500a7eaebd133610c038352911944134#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R4).
