### ISSUE TITLE
[Enchantment] add your gui to ModMenu 

### ISSUE THREAD

**Issue by mastermc05** [Celibistrial/freelook#10]
When I firstly played on the version where the options were in options screen, and it suddenly disappeared, it took me half of an hour to see that you added a keybind to open the config gui, which isn't very pleasant, because when you have lots of mods, you just don't have enough keybinds, for just one config, so adding access to your gui trough mod menu would be very pleasant

**Comment by mastermc05** [comment]
trough a command isn't a better idea too, because it would need to find that you added such a command too, but mod menu has almost everyone

**Comment by Celibistrial** [comment]
I added a keybind because it's almost impossible to guarantee that no other mod is going to mess up the GUI.

**Comment by Celibistrial** [comment]
Ill see if it is possible to add my settings to the mod menu screen.
