### ISSUE TITLE
Suggestion: Head tracking (Tobii/TrackIR/OpenTrack)

### ISSUE THREAD

**Issue by rght925h** [Celibistrial/freelook#18]
Very nice mod, thank you for sharing your work!

Would it be possible to enable a head tracking source, suck as TrackIR or Tobii, to control the freelook?

**Comment by Celibistrial** [comment]
Integrating a head tracking source like TrackIR or Tobii into freelook would probably be hard, not to mention that i dont have any of the equipment required. Sounds cool tho , maybe someone else can tackle this?

**Comment by Celibistrial** [comment]
Will not be implemented due to lack of time
