### ISSUE TITLE
Change to a Custom ID

### ISSUE THREAD

**Issue by SheepCommander** [Celibistrial/freelook#2]
Will crash if another mod, like Beehive Tooltips, was also lazy and did not change the ID from modid to `freelook`

**Comment by SheepCommander** [comment]
once I remove Beehive Tooltips or Freelook it indeed works, and Beehive Tooltips does not have an Issues tab and I don't have twitch so I can't report it to them

**Comment by SheepCommander** [comment]
Well I guess I can open archive and edit the id to freelook, but would like that to be fixed

**Comment by SheepCommander** [comment]
I'd create a pull request but I still haven't figured out how to XD

**Comment by Celibistrial** [comment]
ok ill will change it

**Comment by Celibistrial** [comment]
what id are you referring to exactly?

**Comment by Celibistrial** [comment]
are you referring to my 1.17 freelook mod?

**Comment by Celibistrial** [comment]
I changed mod id for my 1.17 mod and uploaded to new jar to my curseforge page

**Comment by SheepCommander** [comment]
cool I also didn't realize it's the same creator
