### ISSUE TITLE
1.21.3 support? :D

### ISSUE THREAD

**Issue by Nilsson321** [Celibistrial/freelook#23]

**Comment by Chromeyyy** [comment]
Yes please. The mod doesn't work with 1.21.2 and 1.21.3
When you press alt, it goes into freelook, however the mouse has no effect. You move your mouse but the camera is stuck.

**Comment by Celibistrial** [comment]
Will look into it

**Comment by Celibistrial** [comment]
Done! Both version should now be available on modrinth and curseforge

**Comment by Chromeyyy** [comment]
Thank you for the quick fix.
