### ISSUE TITLE
Add issues tag to the fabric.mod.json file.

### ISSUE THREAD

**Issue by RDKRACZ** [Celibistrial/freelook#4]
I would to a pr for this but this repo seems to contain source only for the 1.16 version.

**Comment by RDKRACZ** [comment]
Also the description - "T"

Maybe change it to "Free look from lunar now for fabric"

**Comment by RDKRACZ** [comment]
What about the icon? For now, it's the default from the fabric example mod but the one from the curseforge is ok. I can remove the white background, maybe crop, resize and compress it slightly. What about a grayscale one?

example:
![Screenshot from 2021-08-01 11-05-51](https://user-images.githubusercontent.com/43277609/127765543-c32ebea3-a8a6-46f3-be5f-a4b7c62bbaa9.png)

**Comment by RDKRACZ** [comment]
Or a cursed one?
![Screenshot from 2021-08-01 11-10-22](https://user-images.githubusercontent.com/43277609/127765715-9dce65c7-7ae0-4364-bebf-84f28feb8251.png)
![Screenshot from 2021-08-01 11-10-14](https://user-images.githubusercontent.com/43277609/127765716-2535962c-a834-44b5-a83a-04128368f9cb.png)

**Comment by TheKodeToad** [comment]
1.16 is 1.16+ (including 1.17).

**Comment by TheKodeToad** [comment]
1.16 works with 1.17.

**Comment by TheKodeToad** [comment]
1.16 works with 1.17, so you can do a pull request.

**Comment by Celibistrial** [comment]
> Or a cursed one?
> ![Screenshot from 2021-08-01 11-10-22](https://user-images.githubusercontent.com/43277609/127765715-9dce65c7-7ae0-4364-bebf-84f28feb8251.png)
> ![Screenshot from 2021-08-01 11-10-14](https://user-images.githubusercontent.com/43277609/127765716-2535962c-a834-44b5-a83a-04128368f9cb.png)

I don't really think the mod icon is necessary.
But sure ill change it to the first picture you sent when i have freetime
