### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by EysseW** [Celibistrial/freelook#5]
Love the mod! It's great for content creation as well!!! Would you please update to 1.18?

**Comment by Celibistrial** [comment]
Yea im working on the 1.18 version

**Comment by EysseW** [comment]
Sweat!

**Comment by Celibistrial** [comment]
1.18 is out

**Comment by Celibistrial** [comment]
well the guys at curse forge still have to approve it tho :/

**Comment by EysseW** [comment]
Nice! Thanks a lot! I can also just download from GitHub, no biggie

**Comment by EysseW** [comment]
Wait a second... I forgot about this because of test week, but where is the download found? I only see the code, and I appearently don't have the permissions to gradlew build

**Comment by Celibistrial** [comment]
so u cloned it and tried gradlew build?

**Comment by Celibistrial** [comment]
i think i might have messed something up , but the download (jar file) is there on my curse forge page https://www.curseforge.com/minecraft/mc-mods/freelook-fabric

**Comment by Celibistrial** [comment]
i cloned the 1.18 branch , and ran gradlew build it works just fine
![image](https://user-images.githubusercontent.com/82810795/144732930-be2fad35-4ddc-411f-bbc2-9985fe185ffd.png)

**Comment by EysseW** [comment]
I am on Linux and did ./gradlew build. It told me I had no permission to. On every other build I do it doesn't..

**Comment by RDKRACZ** [comment]
@EysseW looks like you forgot to add executable permission to the gradlew file. That's not really an issue with the mod but it can be fixed on its side.

**Comment by RDKRACZ** [comment]
Did you perhaps recently switch to Linux? You can right-click any file in your file manager and from the permissions tab make it executable for you or for anyone. From a terminal, you can do `chmod +x ./gradlew` or `chmod 755 ./gradlew`.

**Comment by RDKRACZ** [comment]
>On every other build I do it doesn't..

Maybe the devs already made it executable or these were some new mods - fabric-example-mod made gradlew file executable some time ago IIRC.

**Comment by Celibistrial** [comment]
> I am on Linux and did ./gradlew build. It told me I had no permission to. On every other build I do it doesn't..

I have never used linux and cant really help you

**Comment by EysseW** [comment]
Thanks for all the help, but I don't see a 1.18 download on the curseforge and now that I tried to give myself the permissions to open ./graldew, I got a build failed... And FYI, I switched to linux a couple of months ago.

**Comment by Celibistrial** [comment]
![image](https://user-images.githubusercontent.com/82810795/144750986-4510b854-b65c-4b27-b374-d79093ae581f.png)

**Comment by EysseW** [comment]
![image](https://user-images.githubusercontent.com/80292589/144752253-d0ef8337-2f69-43f4-99ab-d720cabad4b1.png)
I was looking at this one... Thanks!
