### ISSUE TITLE
FreeLook main menu button appears right on top of the singleplayer button

### ISSUE THREAD

**Issue by PiTheGuy** [Celibistrial/freelook#8]
The button to switch the FreeLook mode is right on top of the singleplayer button, making it very difficult to read and almost impossible to click
![2021-12-14_16 05 43](https://user-images.githubusercontent.com/55959311/146087196-e828c6e0-c9ff-44f2-94b0-f7dc41ff99ff.png)
.

**Comment by Celibistrial** [comment]
I have moved it into the options menu , let me know if the new build works
